/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ICA2Wenjia;

import java.awt.event.ComponentListener;
import java.awt.Dimension;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author apple
 */
public class MainWindow extends javax.swing.JFrame {
    
    public List<Transactions> tTransactions = new ArrayList<>();
    public List<BBStockItem> bBBStockItemList = null;
    private List<MMStockItem> mMMStockItemList = null;
    /**
     * Creates new form ICAGUIMain
     */
    public MainWindow() {
        initComponents();
        setTitle("Stock Control With Low Stock Reporting");
         // read BBStock and MMStock
        
        try{
            mMMStockItemList = MMStockItem.openCSV("mead_modernity_stock_list_example.csv");
            bBBStockItemList = BBStockItem.openCSV("barkers_boutique_stock_list_example.csv");
        }
        catch (Exception e){
            System.out.print("Error");
        }
        for(MMStockItem item : mMMStockItemList){
            BBStockItem a = new MMStockAdapter(item);
            bBBStockItemList.add(a);
        }
        StockTable.setModel(new BBStockTableModel(bBBStockItemList));   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        StockTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jButton3.setText("jButton3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.PAGE_AXIS));

        StockTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        StockTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(StockTable);

        jPanel1.add(jScrollPane1);

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sell");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Add New Product");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Exit");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(7, 7, 7)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //buy button
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            int BBStockItemListIndex = StockTable.getSelectedRow();
            if(BBStockItemListIndex >= 0){
                int currentQuantity = bBBStockItemList.get(BBStockItemListIndex).getQuantity();
                // get buy aoumnt
                int n = Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity:"));
                bBBStockItemList.get(BBStockItemListIndex).setQuantity(currentQuantity + n);
            }else{
                JOptionPane.showMessageDialog(MainWindow.this, "Please select a product."); 
            }
            StockTable.updateUI();
    }//GEN-LAST:event_jButton1ActionPerformed
    //sell button
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(!bBBStockItemList.isEmpty()){
            int BBStockItemListIndex = StockTable.getSelectedRow();
            if (BBStockItemListIndex >= 0){
                int currentQuantity = bBBStockItemList.get(BBStockItemListIndex).getQuantity();
                if (currentQuantity > 0){
                    //get sale amount
                    int n = Integer.parseInt(JOptionPane.showInputDialog("Please enter the quantity:"));
                    if ((currentQuantity - n <= 6) & (currentQuantity - n >= 0)){
                        JOptionPane.showMessageDialog(MainWindow.this, String.format("%s Quantity left: %d ",bBBStockItemList.get(BBStockItemListIndex).getProductCode(),currentQuantity-n),"Low Stock Alert",2);                 
                        bBBStockItemList.get(BBStockItemListIndex).setQuantity(currentQuantity - n);
                    }                                  
                    if (currentQuantity - n < 0 ){
                        JOptionPane.showMessageDialog(MainWindow.this, "Stock is not enough. Please re-enter the quantity.","Invalid Action",2);    
                        bBBStockItemList.get(BBStockItemListIndex).setQuantity(currentQuantity);
                    }
                    else{bBBStockItemList.get(BBStockItemListIndex).setQuantity(currentQuantity - n);
                            }
                    String productCode = bBBStockItemList.get(BBStockItemListIndex).getProductCode(); 
                    StockTable.updateUI();
                    //???
                    if(!(tTransactions.isEmpty())){
                        for(Transactions a : tTransactions ){
                            if (a.productCode==productCode){
                                a.date = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime());
                                a.quantitySold += n;
                                return;
                            }
                        }
                    }
                    Transactions tempRecord = new Transactions(new SimpleDateFormat("yyyy/MM/dd HH:mm:ss").format(Calendar.getInstance().getTime()),bBBStockItemList.get(BBStockItemListIndex).getProductCode(),n,bBBStockItemList.get(BBStockItemListIndex).getUnitPrice());
                    tTransactions.add(tempRecord);
                    
                }else{
                    JOptionPane.showMessageDialog(MainWindow.this, "Sorry, no avaliable product in stock."); 
                }
            }else{
                    JOptionPane.showMessageDialog(MainWindow.this, "Please select a product."); 

            }
        }else{
            JOptionPane.showMessageDialog(MainWindow.this, "Empty file.","Error",2); 
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    //add button
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         NewProduct frame = new NewProduct();
            frame.setPreferredSize(new Dimension(600, 300));
            frame.addComponentListener(new ComponentAdapter() {
                    public void componentHidden(ComponentEvent e) {
                       bBBStockItemList.add(frame.newItem);
                       StockTable.updateUI();
                    }
            });
            frame.pack();
            frame.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
    }//GEN-LAST:event_jButton5ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable StockTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables


  
}
